### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Shramkoweb** [Shramkoweb/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by shramko-serhii** [comment]
<ul class="contacts">
                    <li>
                      <a href="https://github.com/Shramkoweb" rel="author" class="github" aria-label="Serhii Shramko profile in github">
                        <svg class="icon" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                          <use xlink:href="#img-github-icon"></use>
                        </svg>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.linkedin.com/in/sergey-shramko" rel="author" class="linkedin" aria-label="Serhii Shramko profile in linkedin">
                        <svg class="icon" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                          <use xlink:href="#img-linkedin"></use>
                        </svg>
                      </a>
                    </li>
                    <li>
                      <a href="https://t.me/shramkoweb" rel="author" class="telegram" aria-label="Write to the author in telegram">
                        <svg class="icon" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                          <use xlink:href="#img-telegram"></use>
                        </svg>
                      </a>
                    </li>
                    <li>
                      <a href="mailto:shramko.web@yahoo.com" rel="author" class="mail">
                        <svg class="icon" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                          <use xlink:href="#img-mail-icon"></use>
                        </svg>
                        <span>shramko.web@yahoo.com</span>
                      </a>
                    </li>
                    <li>
                      <a href="tel:+380939339696" rel="author" class="phone">
                        <svg class="icon" viewBox="0 0 320 512" xmlns="http://www.w3.org/2000/svg">
                          <use xlink:href="#img-phone-icon"></use>
                        </svg>
                        <span>+38 (093) 9339696</span>
                      </a>
                    </li>
                  </ul>
