### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Shramkoweb** [Shramkoweb/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by shramko-serhii** [comment]
<h3>Experience</h3>
              <h6>Recent</h6>
                <ul class="timeline">
                  <li class="highlighted">
                    <p><em>March 2020 – present</em></p>
                    <p><strong>Frontend Developer</strong> at <strong><a href="https://www.pdffiller.com/" rel="external">PDFfiller</a></strong></p>
                  </li>
                  <li class="highlighted">
                    <p><em>November 2019 – present</em></p>
                    <p><strong>HTML and CSS tutor</strong> at <strong><a href="https://htmlacademy.ru/" rel="external">HTML Academy</a></strong></p>
                  </li>
                </ul>
              <h6>Back then</h6>
                <ul class="timeline">
                  <li>
                    <p><em>April 2019 – March 2020</em></p>
                    <p><strong>Markup Developer</strong> at <strong><a href="https://www.pdffiller.com/" rel="external">PDFfiller</a></strong></p>
                    <ul>
                      <li>Partial refactor Pug/Jade components to REACT</li>
                      <li>Create UI library for company products</li>
                      <li>Creating pages for web applications</li>
                    </ul>
                  </li>
                  <li>
                    <p><em>December 2018 – April 2019</em></p>
                    <p><strong>Markup Developer</strong> at <strong><a href="https://hexa.com.ua/en/home/" rel="external">Hexa</a></strong></p>
                    <ul>
                      <li>Creating pages for web applications</li>
                    </ul>
                  </li>
                </ul>
