### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Shramkoweb** [Shramkoweb/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by shramko-serhii** [comment]
<div class="six wide column">
              <section>
                <h3>Languages</h3>
                <p class="tags small">
                  
                  <span class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА трішечки</span></span>
                  <span class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></span>
                  <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH a bit 😸</span></p>
              </section>
              <section>
                <h3>Skills</h3>
                <p class="tags small">
                  HTML CSS JS JEST ENZYME REACT REDUX A11Y
                  SASS PHOTOSHOP ZEPLIN LODASH GULP WEBPACK NPM BASH
                  CLI BASH ESLINT
                </p>
              </section>
              <section>
                <h3>DESIRE</h3>
                <p class="tags small bulleted">
                  <span class="tag">TO BE GREAT DEVELOPER</span>
                  <span class="tag">TO READ MORE</span>
                  <span class="tag">TO BE FIT AND HEALTHY</span>
                  <span class="tag">TO LISTEN AND LEARN</span>
                </p>
              </section>
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>Every day</em></div>
                    <p class="tags bulleted">
                      <span class="tag"><a href="https://ru.hexlet.io/" rel="external"><strong>Hexlet</strong></a></span>
                      <span class="tag"><a href="https://www.udemy.com/" rel="external"><strong>Udemy</strong></a></span>
                      <span class="tag"><a href="https://egghead.io/" rel="external"><strong>egghead.io</strong></a></span>
                      <span class="tag"><a href="https://www.udacity.com/" rel="external"><strong>Udacity</strong></a></span>
                      <span class="tag"><a href="https://frontendmasters.com/" rel="external"><strong>Frontendmasters</strong></a></span>
                      <span class="tag"><a href="https://www.youtube.com/" rel="external"><strong>Youtube</strong></a></span>
                    </p>
                  </li>
                  <li>
                  <li>
                    <div><em>August 2018 &ndash; December 2019</em></div>
                    <div><strong>Completed all JS/REACT and HTML/CSS courses</strong> at <a href="https://htmlacademy.ru/profile/id852139/certificates" rel="external"><strong>HTML Academy</strong></a></div>
                  </li>
                  <li>
                    <div><em>2013 &ndash; 2016</em></div>
                    <div><strong>Master degree</strong> in <strong>Electromechanical Systems of Automation and Electric Drive</strong> at <a href="http://www.nmu.org.ua/en/" rel="external"><strong>National Mining University</strong></a></div>
                  </li>
                </ul>
              </section>
              <section>
                <h3>Articles</h3>
                <p>Not published <sup><em>yet</em></sup></p>
              </section>
            </div>

**Comment by shramko-serhii** [comment]
=)

**Comment by Shramkoweb** [comment]
<div class="six wide column">
              <section>
                <h3>Languages</h3>
                <p class="tags small">
                  
                  <span class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА трішечки</span></span>
                  <span class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></span>
                  <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH a bit 😸</span></p>
              </section>
              <section>
                <h3>Skills</h3>
                <p class="tags small">
                  HTML CSS JS JEST ENZYME REACT REDUX A11Y
                  SASS PHOTOSHOP ZEPLIN LODASH GULP WEBPACK NPM BASH
                  CLI BASH ESLINT
                </p>
              </section>
              <section>
                <h3>DESIRE</h3>
                <p class="tags small bulleted">
                  <span class="tag">TO BE GREAT DEVELOPER</span>
                  <span class="tag">TO READ MORE</span>
                  <span class="tag">TO BE FIT AND HEALTHY</span>
                  <span class="tag">TO LISTEN AND LEARN</span>
                </p>
              </section>
              <section>
                <h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <div><em>Every day</em></div>
                    <p class="tags bulleted">
                      <span class="tag"><a href="https://ru.hexlet.io/" rel="external"><strong>Hexlet</strong></a></span>
                      <span class="tag"><a href="https://www.udemy.com/" rel="external"><strong>Udemy</strong></a></span>
                      <span class="tag"><a href="https://egghead.io/" rel="external"><strong>egghead.io</strong></a></span>
                      <span class="tag"><a href="https://www.udacity.com/" rel="external"><strong>Udacity</strong></a></span>
                      <span class="tag"><a href="https://frontendmasters.com/" rel="external"><strong>Frontendmasters</strong></a></span>
                      <span class="tag"><a href="https://www.youtube.com/" rel="external"><strong>Youtube</strong></a></span>
                    </p>
                  </li>
                  <li>
                  <li>
                    <div><em>August 2018 &ndash; December 2019</em></div>
                    <div><strong>Completed all JS/REACT and HTML/CSS courses</strong> at <a href="https://htmlacademy.ru/profile/id852139/certificates" rel="external"><strong>HTML Academy</strong></a></div>
                  </li>
                  <li>
                    <div><em>2013 &ndash; 2016</em></div>
                    <div><strong>Master degree</strong> in <strong>Electromechanical Systems of Automation and Electric Drive</strong> at <a href="http://www.nmu.org.ua/en/" rel="external"><strong>National Mining University</strong></a></div>
                  </li>
                </ul>
              </section>
              <section>
                <h3>Articles</h3>
                <p>Not published <sup><em>yet</em></sup></p>
              </section>
            </div>
